overwrite: true
schema: http://localhost:4000/graphql
documents: "./src/**/*.graphql"
generates:
  src/types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
